version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

commands:
  restore-docker:
    description: Restore Docker image cache
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          key: v1-{{.Branch}}
      - run:
          name: Restore Docker image cache
          command: docker load -i /cache/docker.tar

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: docker build -t app:build .
      - run:
          name: docker save app:build
          command: mkdir -p /cache; docker save -o /cache/docker.tar "app:build"
      - save_cache:
          key: v1-{{ .Branch }}-{{epoch}}
          paths:
            - /cache/docker.tar

  test:
    docker:
      - image: docker:stable-git
    steps:
      - restore-docker
      - run:
          name: Test Code
          command: docker run app:build yarn test
      - run:
          name: Lint Code
          command: docker run app:build yarn lint

workflows:
  main:
    jobs:
      - build

      - test:
          requires:
            - build

      - gcp-gcr/build-and-push-image:
          # See https://bugzilla.mozilla.org/show_bug.cgi?id=1608958 for details
          context: data-eng-airflow-gcr
          image: app-store-analytics-export
          requires:
            - test
          filters:
            branches:
              only: main
